apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharecare-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharecare-user
  template:
    metadata:
      labels:
        app: sharecare-user
    spec:
      containers:
      - name: sharecare-user-pod
        image: 996886234804.dkr.ecr.eu-central-1.amazonaws.com/sharecare/user:1.0
        env:
        - name: DATABASE_HOST
          value: totipulocationsvcdb.postgres.database.azure.com
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: sharecare-user
        - name: DATABASE_USERNAME
          value: totipu@totipulocationsvcdb
        - name: DATABASE_PASSWORD
          value: industrija2!
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: sharecare-user-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: sharecare-user
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sharecare-user-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: multicloud.tipuric.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: sharecare-user-svc
                port:
                  number: 80
            path: /users