const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "Multi-cloud Workshop User API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    tags: [
        {
            "name": "Users",
            "description": "APIs for managing users"
        }
    ],
    definitions: {
        User: {
            firstName: "John",
            lastName: "Doe",
            eMail: "john@doe.com",
            password: "123456",
            age: 36
        }
    }

}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/users/users.router.js']

swaggerAutogen(outputFile, endpointsFiles, doc)