apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharecare-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharecare-user
  template:
    metadata:
      labels:
        app: sharecare-user
    spec:
      containers:
      - name: sharecare-user-pod
        image: totipuacr.azurecr.io/sharecare-user:0.1
        env:
        - name: DATABASE_HOST
          value: totipulocationsvcdb.postgres.database.azure.com
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: sharecare-user
        - name: DATABASE_USERNAME
          value: totipu@totipulocationsvcdb
        - name: DATABASE_PASSWORD
          value: industrija2!
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: sharecare-user-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: sharecare-user
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sharecare-user-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sharecare.tipuric.com
    http:
      paths:
      - backend:
          serviceName: sharecare-user-svc
          servicePort: 80
        path: /users